# Generated by Django 3.1.7 on 2021-03-15 16:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='generi_preferiti',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Commedia', 'Commedia'), ('Fantascienza', 'Fantascienza'), ('Horror', 'Horror'), ('Romantico', 'Romantico'), ('Azione', 'Azione'), ('Thriller', 'Thriller'), ('Drammatico', 'Drammatico'), ('Mistero', 'Mistero'), ('Giallo', 'Giallo'), ('Animazione', 'Animazione'), ('Avventura', 'Avventura'), ('Fantasy', 'Fantasy'), ('Supereroi', 'Supereroi'), ('Storico', 'Storico'), ('Biografico', 'Biografico'), ('Documentario', 'Documentario'), ('Musical', 'Musical'), ('Guerra', 'Guerra'), ('Western', 'Western')], max_length=300),
        ),
    ]
