# Generated by Django 3.1.7 on 2021-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='feedback_guidatore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='feedback_user',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='generi_preferiti',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='posti_macchina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sesso',
            field=models.CharField(default='', max_length=10),
        ),
    ]
