# Generated by Django 3.1.7 on 2021-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0002_auto_20210303_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='eta',
        ),
        migrations.AddField(
            model_name='profile',
            name='data_nascita',
            field=models.DateField(null=True),
        ),
    ]
