# Generated by Django 3.1.7 on 2021-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0002_auto_20210315_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='posti_macchina',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
