# Generated by Django 3.1.7 on 2021-03-04 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.CharField(choices=[('VC', 'Victoria Cinema'), ('CR', 'Cinema Raffaello'), ('CA', 'Cinema Astra')], max_length=100)),
                ('film', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('orario', models.TimeField()),
                ('limite_persone', models.PositiveSmallIntegerField()),
                ('genere', models.CharField(choices=[('Commedia', 'Commedia'), ('Fantascienza', 'Fantascienza'), ('Horror', 'Horror'), ('Romantico', 'Romantico'), ('Azione', 'Azione'), ('Thriller', 'Thriller'), ('Drammatico', 'Drammatico'), ('Mistero', 'Mistero'), ('Giallo', 'Giallo'), ('Animazione', 'Animazione'), ('Avventura', 'Avventura'), ('Fantasy', 'Fantasy'), ('Commedia romantica', 'Commedia romantica'), ("Commedia d'azione", "Commedia d'azione"), ('Supereroi', 'Supereroi'), ('Storico', 'Storico'), ('Biografico', 'Biografico'), ('Documentario', 'Documentario'), ('Musical', 'Musical'), ('Guerra', 'Guerra'), ('Western', 'Western')], max_length=100)),
                ('commento', models.TextField()),
                ('data_invito', models.DateTimeField(default=django.utils.timezone.now)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inviti',
            },
        ),
    ]
