# Generated by Django 3.1.7 on 2021-03-13 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.CharField(choices=[('Victoria Cinema', 'Victoria Cinema'), ('Cinema Raffaello', 'Cinema Raffaello'), ('Cinema Astra', 'Cinema Astra')], max_length=100)),
                ('film', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('orario', models.TimeField()),
                ('limite_persone', models.PositiveSmallIntegerField()),
                ('genere', multiselectfield.db.fields.MultiSelectField(choices=[('Commedia', 'Commedia'), ('Fantascienza', 'Fantascienza'), ('Horror', 'Horror'), ('Romantico', 'Romantico'), ('Azione', 'Azione'), ('Thriller', 'Thriller'), ('Drammatico', 'Drammatico'), ('Mistero', 'Mistero'), ('Giallo', 'Giallo'), ('Animazione', 'Animazione'), ('Avventura', 'Avventura'), ('Fantasy', 'Fantasy'), ('Supereroi', 'Supereroi'), ('Storico', 'Storico'), ('Biografico', 'Biografico'), ('Documentario', 'Documentario'), ('Musical', 'Musical'), ('Guerra', 'Guerra'), ('Western', 'Western')], max_length=100)),
                ('commento', models.TextField(blank=True)),
                ('data_invito', models.DateTimeField(default=django.utils.timezone.now)),
                ('partecipanti', models.ManyToManyField(blank=True, related_name='partecipanti', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invito',
                'verbose_name_plural': 'Inviti',
            },
        ),
    ]
