# Generated by Django 3.1.7 on 2021-03-09 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inviti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invito',
            options={'verbose_name': 'Invito', 'verbose_name_plural': 'Inviti'},
        ),
        migrations.AddField(
            model_name='invito',
            name='partecipanti',
            field=models.ManyToManyField(blank=True, related_name='partecipanti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invito',
            name='posti_rimanenti',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invito',
            name='cinema',
            field=models.CharField(choices=[('Victoria Cinema', 'Victoria Cinema'), ('Cinema Raffaello', 'Cinema Raffaello'), ('Cinema Astra', 'Cinema Astra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invito',
            name='genere',
            field=models.CharField(choices=[('Commedia', 'Commedia'), ('Fantascienza', 'Fantascienza'), ('Horror', 'Horror'), ('Romantico', 'Romantico'), ('Azione', 'Azione'), ('Thriller', 'Thriller'), ('Drammatico', 'Drammatico'), ('Mistero', 'Mistero'), ('Giallo', 'Giallo'), ('Animazione', 'Animazione'), ('Avventura', 'Avventura'), ('Fantasy', 'Fantasy'), ('Supereroi', 'Supereroi'), ('Storico', 'Storico'), ('Biografico', 'Biografico'), ('Documentario', 'Documentario'), ('Musical', 'Musical'), ('Guerra', 'Guerra'), ('Western', 'Western')], max_length=100),
        ),
    ]
