# Generated by Django 3.1.7 on 2021-03-15 16:55

from django.db import migrations, models
import inviti.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inviti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invito',
            name='data',
            field=models.DateField(validators=[inviti.validators.validate_date]),
        ),
    ]
