# Generated by Django 3.1.7 on 2021-03-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviti', '0002_auto_20210313_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invito',
            name='data',
            field=models.DateField(),
        ),
    ]
