# Generated by Django 3.1.7 on 2021-03-15 17:33

from django.db import migrations, models
import inviti.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inviti', '0003_auto_20210315_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invito',
            name='data',
            field=models.DateField(validators=[inviti.validators.validate_date]),
        ),
    ]
