class Anagrafica:
    ListaProvince = [('AG', 'AG'), ('AL', 'AL'), ('AN', 'AN'), ('AO', 'AO'), ('AP', 'AP'), ('AQ', 'AQ'), ('AR', 'AR'),
                ('AT', 'AT'), ('AV', 'AV'), ('BA', 'BA'), ('BG', 'BG'), ('BI', 'BI'), ('BL', 'BL'), ('BN', 'BN'),
                ('BO', 'BO'), ('BR', 'BR'), ('BS', 'BS'), ('BT', 'BT'), ('BZ', 'BZ'), ('CA', 'CA'), ('CB', 'CB'),
                ('CE', 'CE'), ('CH', 'CH'), ('CL', 'CL'), ('CN', 'CN'), ('CO', 'CO'), ('CR', 'CR'), ('CS', 'CS'),
                ('CT', 'CT'), ('CZ', 'CZ'), ('EN', 'EN'), ('FC', 'FC'), ('FE', 'FE'), ('FG', 'FG'), ('FI', 'FI'),
                ('FM', 'FM'), ('FR', 'FR'), ('GE', 'GE'), ('GO', 'GO'), ('GR', 'GR'), ('IM', 'IM'), ('IS', 'IS'),
                ('KR', 'KR'), ('LC', 'LC'), ('LE', 'LE'), ('LI', 'LI'), ('LO', 'LO'), ('LT', 'LT'), ('LU', 'LU'),
                ('MB', 'MB'), ('MC', 'MC'), ('ME', 'ME'), ('MI', 'MI'), ('MN', 'MN'), ('MO', 'MO'), ('MS', 'MS'),
                ('MT', 'MT'), ('NO', 'NO'), ('NU', 'NU'), ('OR', 'OR'), ('PA', 'PA'), ('PC', 'PC'), ('PD', 'PD'),
                ('PE', 'PE'), ('PG', 'PG'), ('PI', 'PI'), ('PN', 'PN'), ('PO', 'PO'), ('PR', 'PR'), ('PT', 'PT'),
                ('PU', 'PU'), ('PV', 'PV'), ('PZ', 'PZ'), ('RA', 'RA'), ('RC', 'RC'), ('RE', 'RE'), ('RG', 'RG'),
                ('RI', 'RI'), ('RM', 'RM'), ('RN', 'RN'), ('RO', 'RO'), ('SA', 'SA'), ('SI', 'SI'), ('SO', 'SO'),
                ('SP', 'SP'), ('SR', 'SR'), ('SS', 'SS'), ('SU', 'SU'), ('SV', 'SV'), ('TA', 'TA'), ('TE', 'TE'),
                ('TN', 'TN'), ('TO', 'TO'), ('TP', 'TP'), ('TR', 'TR'), ('TS', 'TS'), ('TV', 'TV'), ('UD', 'UD'),
                ('VA', 'VA'), ('VB', 'VB'), ('VC', 'VC'), ('VE', 'VE'), ('VI', 'VI'), ('VR', 'VR'), ('VT', 'VT'),
                ('VV', 'VV')]

    ListaRegioni = [('Abruzzo', 'Abruzzo'), ('Basilicata', 'Basilicata'), ('Calabria', 'Calabria'),
                ('Campania', 'Campania'), ('Emilia-Romagna', 'Emilia-Romagna'),
                ('Friuli-Venezia Giulia', 'Friuli-Venezia Giulia'), ('Lazio', 'Lazio'), ('Liguria', 'Liguria'),
                ('Lombardia', 'Lombardia'), ('Marche', 'Marche'), ('Molise', 'Molise'), ('Piemonte', 'Piemonte'),
                ('Puglia', 'Puglia'), ('Sardegna', 'Sardegna'), ('Sicilia', 'Sicilia'), ('Toscana', 'Toscana'),
                ('Trentino-Alto Adige', 'Trentino-Alto Adige'), ('Umbria', 'Umbria'),
                ("Valle d'Aosta", "Valle d'Aosta"), ('Veneto', 'Veneto')]
